packageExtensions:
  jest-cli@*:
    dependencies:
      "@jest/console": "*"
      "@jest/reporters": "*"
  jest-config@*:
    dependencies:
      jest-runtime: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
